spring.datasource.url=jdbc:postgresql://localhost:5432/msdevdb
spring.datasource.username=msdev
spring.datasource.password=msdevpass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.security.user.name=stackuser
spring.security.user.password=123456

jwt.secretKey=dev-secret-key