spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 667000579416-e9u96iro7gm5j93epdtu5bks4858lo52.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile