spring.application.name=MindStack

server.port=${PORT:8080}

#How Hibernate manages the database schema at application startup.
# update:Compares your @Entity classes with the existing database schema
#       Adds missing tables/columns
#       Does not delete existing data, not drop unused columns
spring.jpa.hibernate.ddl-auto=update

#Prints executed SQL queries in the console.
spring.jpa.show-sql=true

#Formats the SQL printed by show-sql.
spring.jpa.properties.hibernate.format_sql=true

#dialect tells Hibernate: "Generate SQL optimized for PostgreSQL."
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Whether Spring runs SQL scripts at startup. (data.sql && schema.sql)
#spring.sql.init.mode=always

#Wait until Hibernate finishes creating/updating the schema, then run SQL initialization scripts.
#spring.jpa.defer-datasource-initialization=true

spring.thymeleaf.check-template-location=false
