spring.application.name=MindStack

server.port=${PORT:8080}

#How Hibernate manages the database schema at application startup.
# update:Compares your @Entity classes with the existing database schema
#       Adds missing tables/columns
#       Does not delete existing data, not drop unused columns
spring.jpa.hibernate.ddl-auto=update

#Maximum number of DB connections the pool can create (upper concurrency limit to DB).
spring.datasource.hikari.maximum-pool-size=10

#Minimum number of idle (ready-to-use) connections kept alive in pool.
spring.datasource.hikari.minimum-idle=2

#Maximum time (ms) a request will wait to get a DB connection before failing.
spring.datasource.hikari.connection-timeout=30000

#Time (ms) an idle connection can stay unused before being closed.
spring.datasource.hikari.idle-timeout=600000

#dialect tells Hibernate: "Generate SQL optimized for PostgreSQL."
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Whether Spring runs SQL scripts at startup. (data.sql && schema.sql)
#spring.sql.init.mode=always

#Wait until Hibernate finishes creating/updating the schema, then run SQL initialization scripts.
#spring.jpa.defer-datasource-initialization=true


#Meaning: If ENV not present ? use default
app.frontend.url=${FRONTEND_URL:http://localhost:5173}
server.host.url=${SERVER_HOST_URL:http://localhost:8080}

spring.jpa.open-in-view=false
spring.thymeleaf.enabled=false
spring.thymeleaf.check-template-location=false